# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=200)),
                ('layer_title', models.CharField(max_length=200)),
                ('layer_abstract', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_title', models.CharField(max_length=200)),
                ('service_URL', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Service'),
        ),
    ]
