# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_abstract',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
